NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER=""
TRANSFER_SERVER=""
SIGNING_KEY="GBBCZFSYPTQPCYP7ZAHR3JTATOND5CGS7ENRAGGQSVN33UOQN42EFQQO"
HORIZON_URL="https://horizon.stellar.org/accounts/GBBCZFSYPTQPCYP7ZAHR3JTATOND5CGS7ENRAGGQSVN33UOQN42EFQQO"
ACCOUNTS=[
"GDWAQUTNLSFDPSQ37VS5KRUI3CJ6IXLNUO2PES3R3HVIKPCTAE6R4JFZ",
"GBBCZFSYPTQPCYP7ZAHR3JTATOND5CGS7ENRAGGQSVN33UOQN42EFQQO"

]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Dave's Tokin' Token"
ORG_DBA=""
ORG_URL="https://thepeaceprojectmeditations.com/"
ORG_LOGO="https://s3-us-west-2.amazonaws.com/anchor-generated-image-bank/production/podcast_uploaded_nologo400/1542694/1542694-1552433860133-6a4283e2d8339.jpg"
ORG_DESCRIPTION="David Bryan Winnyk (owner of the peace project meditations) has issued these tokens to give you the oppurtunity to toke with him."
ORG_PHYSICAL_ADDRESS="2918 N Clark St, Chicago IL, 60657"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER="1 (234) 562-2133"
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE="davewinnyk"
ORG_TWITTER="fakedavewinnyk"
ORG_GITHUB=""
ORG_OFFICIAL_EMAIL="davewinnyk@gmail.com"

[[PRINCIPALS]]
name="David Bryan Winnyk"
email="davewinnyk@gmail.com"
keybase="davewinnyk"
twitter="fakedavewinnyk"
github=""
id_photo_hash=""
verification_photo_hash=""

[[CURRENCIES]]
code="USD"
issuer="GCZJM35NKGVK47BB4SPBDV25477PZYIYPVVG453LPYFNXLS3FGHDXOCM"
display_decimals=2

[[CURRENCIES]]
code="BTC"
issuer="GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U"
display_decimals=7
anchor_asset_type="crypto"
anchor_asset="BTC"
redemption_instructions="Use SEP6 with our federation server"
collateral_addresses=["2C1mCx3ukix1KfegAY5zgQJV7sanAciZpv"]
collateral_address_signatures=["304502206e21798a42fae0e854281abd38bacd1aeed3ee3738d9e1446618c4571d10"]

# asset with meta info
[[CURRENCIES]]
code="DTT"
issuer="GDWAQUTNLSFDPSQ37VS5KRUI3CJ6IXLNUO2PES3R3HVIKPCTAE6R4JFZ"
display_decimals=2
name="Dave's Tokin' Token"
desc="1 DTT entitles the barer to 1 toke with David Bryan Winnyk."
conditions="There will only ever be 49 DTT tokens in existence. You must travel to David to receive your toke. David can deny your toke for any reason, so please contact him before using."
image=""
fixed_number=49